import { test, expect } from '@playwright/test';
import catalog from '../../public/data/storefronts.json' with { type: 'json' };

test('walk inside a venue, inspect exhibits, and switch to the outdoor mall', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/?place=studio-ix&walk=1');
  await expect(page.locator('#room-world')).toHaveAttribute('data-ready', 'true', { timeout: 90000 });
  await page.getByRole('button', { name: 'Walk inside', exact: true }).click();
  await expect(page.locator('#room-dialog')).toHaveClass(/is-walking/);
  const canvas = page.locator('#room-world canvas');
  const heading = await canvas.getAttribute('data-heading');
  const rect = (await canvas.boundingBox())!;
  await page.mouse.move(rect.x + rect.width * .5, rect.y + rect.height * .5);
  await page.mouse.down(); await page.mouse.move(rect.x + rect.width * .5 + 100, rect.y + rect.height * .5, { steps: 5 }); await page.mouse.up();
  await expect(canvas).not.toHaveAttribute('data-heading', heading!);
  await page.getByRole('button', { name: 'Entrance', exact: true }).click();
  const start = await page.locator('#room-world canvas').getAttribute('data-position');
  await page.keyboard.down('w'); await page.waitForTimeout(800); await page.keyboard.up('w');
  await expect(page.locator('#room-world canvas')).not.toHaveAttribute('data-position', start!);
  await page.getByRole('button', { name: 'Exhibits', exact: true }).click();
  await page.locator('[data-exhibit="event"]').click();
  await expect(page.locator('#surface-details')).toBeVisible();
  await expect(page.locator('#surface-details-body')).toContainText('AI Design Bake-Off');
  await page.getByRole('button', { name: 'Close discovery' }).click();
  await page.getByRole('button', { name: 'Read the exhibits', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'AI Design Bake-Off', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Back to the city' }).click();
  await page.locator('[data-destination="downtown-mall"]').click();
  await page.getByRole('button', { name: 'Walk the Downtown Mall', exact: true }).click();
  await expect(page.locator('#room-world')).toHaveAttribute('data-ready', 'true');
  await expect(page.locator('#room-location-name')).toContainText('OUTDOOR WALK');
  await expect(page.locator('#room-dialog')).toHaveClass(/is-walking/);
  await page.getByRole('button', { name: 'Places', exact: true }).click();
  await page.locator('[data-business="paramount-theater"]').click();
  await expect(page.locator('#surface-interact')).toContainText('The Paramount Theater');
  await page.keyboard.press('e');
  await expect(page.locator('#surface-details-body')).toContainText('215 East Main Street');
  await expect(page.locator('#surface-details-body img')).toBeVisible();
  await page.getByRole('button', { name: 'Close discovery' }).click();
  const mallCanvas = page.locator('#room-world canvas');
  const mallRect = (await mallCanvas.boundingBox())!;
  await mallCanvas.click({ position: { x: mallRect.width / 2, y: mallRect.height * .32 } });
  await expect(page.locator('#surface-details')).toBeVisible();
  await expect(page.locator('#surface-details-body')).toContainText('The Paramount Theater');
  await page.getByRole('button', { name: 'Close discovery' }).click();
  await page.getByRole('button', { name: 'Back to the city' }).click();
  await expect(page.locator('#room-dialog')).toBeHidden();
  await page.getByRole('searchbox').fill('Kardinal Hall');
  await page.getByRole('searchbox').press('Enter');
  await page.getByRole('button', { name: 'Enter the community room' }).click();
  await expect(page.locator('#room-world')).toHaveAttribute('data-ready', 'true');
  await expect(page.getByRole('heading', { name: 'First Wednesdays', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Walk inside', exact: true }).click();
  await page.getByRole('button', { name: 'Exhibits', exact: true }).click();
  await page.locator('[data-exhibit="event"]').click();
  await expect(page.locator('#surface-details-body')).toContainText('October 7, 2026');
  expect(errors).toEqual([]);
});

test('JSON-only storefront edits refresh in the viewer and invalid edits retain the current scene', async ({ page }) => {
  await page.goto('/?place=downtown-mall&walk=1&business=new-dominion-bookshop');
  await expect(page.locator('#room-world')).toHaveAttribute('data-ready', 'true', { timeout: 90000 });
  await expect(page.locator('#surface-interact')).toContainText('New Dominion Bookshop');
  const next = structuredClone(catalog); next.revision++;
  next.businesses[0].name = 'A Fresh Coffee Sign';
  await page.route('**/data/storefronts.json', route => route.fulfill({ json: next }));
  await page.getByRole('button', { name: 'Refresh storefronts', exact: true }).click();
  await expect(page.locator('#surface-status')).toContainText(`revision ${next.revision}`);
  await page.getByRole('button', { name: 'Places', exact: true }).click();
  await expect(page.locator('[data-business="mudhouse-downtown"]')).toContainText('A Fresh Coffee Sign');
  await page.locator('[data-business="mudhouse-downtown"]').click();
  await page.keyboard.press('e');
  await expect(page.locator('#surface-details-body')).toContainText('A Fresh Coffee Sign');
  await page.getByRole('button', { name: 'Close discovery' }).click();
  await page.unroute('**/data/storefronts.json');
  await page.route('**/data/storefronts.json', route => route.fulfill({ json: { ...next, schemaVersion: 99 } }));
  await page.getByRole('button', { name: 'Refresh storefronts', exact: true }).click();
  await expect(page.locator('#surface-status')).toContainText('Keeping the current streetscape');
  await page.getByRole('button', { name: 'Places', exact: true }).click();
  await expect(page.locator('[data-business="mudhouse-downtown"]')).toContainText('A Fresh Coffee Sign');
});

test('touch walking and storefront directory work on a phone', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const page = await context.newPage();
  await page.goto('/?place=downtown-mall&walk=1');
  await expect(page.locator('#room-world')).toHaveAttribute('data-ready', 'true', { timeout: 90000 });
  await expect(page.getByRole('button', { name: 'Walk forward', exact: true })).toBeVisible();
  const before = await page.locator('#room-world canvas').getAttribute('data-position');
  const forward = (await page.getByRole('button', { name: 'Walk forward', exact: true }).boundingBox())!;
  const touch = await context.newCDPSession(page);
  await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: forward.x + forward.width / 2, y: forward.y + forward.height / 2, id: 1 }] });
  await page.waitForTimeout(600);
  await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await expect(page.locator('#room-world canvas')).not.toHaveAttribute('data-position', before!);
  await page.getByRole('button', { name: 'Places', exact: true }).tap();
  await page.locator('[data-business="new-dominion-bookshop"]').tap();
  await expect(page.locator('#surface-interact')).toContainText('New Dominion Bookshop');
  await page.locator('#surface-interact').tap();
  await expect(page.locator('#surface-details-body')).toContainText('404 East Main Street');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && scrollY === 0)).toBe(true);
  await context.close();
});

test('mall businesses and photograph credits are crawlable without JavaScript', async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false });
  const page = await context.newPage();
  await page.goto('/mall/');
  await expect(page.getByRole('heading', { name: 'Photographs & credits' })).toBeVisible();
  await expect(page.locator('.mall-photo-grid img')).toHaveCount(4);
  await page.goto('/mall/new-dominion-bookshop/');
  await expect(page.getByRole('heading', { name: 'New Dominion Bookshop.' })).toBeVisible();
  const data = JSON.parse(await page.locator('script[type="application/ld+json"]').textContent() ?? '{}');
  expect(data.address.streetAddress).toBe('404 East Main Street');
  await context.close();
});
